# Generated by Django 5.2.5 on 2025-08-06 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscrapper.companydetails')),
            ],
        ),
    ]
